///////////////////////////////////////////////////////////
//  BaseHUD.cs
//  Implementation of the Class BaseHUD
//  Generated by Enterprise Architect
//  Created on:      19-dez-2014 14:59:44
//  Original author: Hugo
///////////////////////////////////////////////////////////




using CoreUI;
namespace CoreUI
{
    public class BaseHUD : BaseAnimatedUI
    {
        public override bool IsPage()
        {
            return true;
        }


    }//end BaseHUD

}//end namespace CoreUI