///////////////////////////////////////////////////////////
//  BasePopup.cs
//  Implementation of the Class BasePopup
//  Generated by Enterprise Architect
//  Created on:      19-dez-2014 14:59:43
//  Original author: Hugo
///////////////////////////////////////////////////////////




using CoreUI;
using UnityEngine;
using UnityEngine.UI;
namespace CoreUI
{
    /// <summary>
    /// A popup means some kind of messages. Normally appears on the screen with focus
    /// on it
    /// </summary>
    public class BasePopup : BaseAnimatedUI
    {
        [SerializeField] private Button m_btnClose;
        [SerializeField] private Text m_txtTitle;

        private OnButtonClick m_pOnClickClose;

        public OnButtonClick OnClickClose
        {
            get { return m_pOnClickClose; }
            set { m_pOnClickClose = value; }
        }

        public string Title
        {
            get { return m_txtTitle.text; }
            set { m_txtTitle.text = value; }
        }

        protected override void Start()
        {
            base.Start();
            m_btnClose.onClick.AddListener(OnCloseClick);
        }

        protected void OnCloseClick()
        {
            Close();
            if (m_pOnClickClose != null)
                m_pOnClickClose();
        }


    }//end BasePopup

}//end namespace CoreUI