///////////////////////////////////////////////////////////
//  IBaseUI.cs
//  Implementation of the Interface IBaseUI
//  Generated by Enterprise Architect
//  Created on:      19-dez-2014 14:30:30
//  Original author: Hugo
///////////////////////////////////////////////////////////


namespace CoreUI
{

    public delegate void OnUICompleteEvent(IBaseUI pUI);
    public delegate void OnButtonClick();

    /// <summary>
    /// This interface communicates with an extensions of uis.
    /// </summary>
    public interface IBaseUI
    {

        /// <summary>
        /// shows the UI
        /// </summary>
        /// <param name="OnShow"></param>
        void Show(OnUICompleteEvent OnShow = null);

        /// <summary>
        /// close the UI
        /// </summary>
        /// <param name="OnClose"></param>
        void Close(OnUICompleteEvent OnClose = null);

        /// <summary>
        /// set its visibility
        /// </summary>
        /// <param name="bVisible"></param>
        void SetVisible(bool bVisible);

        /// <summary>
        /// is the UI visible?
        /// </summary>
        /// <returns></returns>
        bool IsVisible();

        /// <summary>
        /// is the UI visible and working?
        /// </summary>
        /// <returns></returns>
        bool IsWorking();

        /// <summary>
        /// used for analytics purpoises.
        ///  when open a page, it will log an event saying about current screen
        /// </summary>
        /// <returns> false by default</returns>
        bool IsPage();

    }//end IBaseUI

}//end namespace CoreUI